---
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
  - directory: "/.devcontainer"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/.devcontainer"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
  - directory: "/examples/federated-learning/tff/worker"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/examples/federated-learning/tff/worker"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
  - directory: "/terraform"
    package-ecosystem: "terraform"
    schedule:
      interval: "daily"
version: 2
...
