---
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
  - directory: "/terraform"
    package-ecosystem: "terraform"
    schedule:
      interval: "daily"
version: 2
...
