---
apiVersion: v1
kind: Service
metadata:
  name: nvflare
  namespace: nvflare
  labels:
    run: nvflare
spec:
  ports:
    - port: 8002
      protocol: TCP
      targetPort: 8002
      name: flport
    - port: 8003
      protocol: TCP
      targetPort: 8003
      name: adminport
  selector:
    run: nvflare-server
