spring:
  application:
    name: odp-client

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: readinessState
        liveness:
          include: livenessState

odp:
  client:
    serviceUrl: ${ODP_SERVICE_URL}
    clientId: ${CLIENT_ID}
    polling-interval: 60000
    timeout: 30s
    max-retries: 3
    retry-delay: 1s
