apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-env-modelupdater-hpa #kpt
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-env-modelupdater #kpt
  metrics:
    - type: External
      external:
        metric:
          name: pubsub.googleapis.com|subscription|num_undelivered_messages
          selector:
            matchLabels:
              "resource.labels.subscription_id": "modelupdater-demo-env-subscription" #kpt
        target:
          type: "AverageValue"
          averageValue: "2"