apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-env-taskassignment-hpa #kpt
spec:
  minReplicas: 4
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-env-taskassignment #kpt
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: "Utilization"
          averageUtilization: 70