apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-env-aggregator-hpa #kpt
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-env-aggregator #kpt
  metrics:
    - type: External
      external:
        metric:
          name: pubsub.googleapis.com|subscription|num_undelivered_messages
          selector:
            matchLabels:
              "resource.type": "pubsub_subscription" #kpt
              "resource.labels.subscription_id": "aggregator-demo-env-subscription" #kpt
        target:
          type: "AverageValue"
          averageValue: "2"