apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-env-collector #kpt
  labels:
    app: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      serviceAccountName: demo-env-gke-wi #kpt
      containers:
      - name: demo-env-collector #kpt
        image: europe-west1-docker.pkg.dev/lgu-demos/federated-learning-cross-device/collector@sha256:b4c692bacb4d1171ebcc49e96ad762969f966ea92fb2f7afc9e31a9c83e67c4d #kpt
        env:
          - name: "FCP_OPTS"
            value: "--project_id 'lgu-demos' --spanner_instance 'fcp-task-demo-env' --task_database_name 'fcp-task-db-demo-env' --client_gradient_bucket_template 'fcp-demo-env-g-%d' --aggregated_gradient_bucket_template 'fcp-demo-env-a-%d' --model_bucket_template 'fcp-demo-env-m-%d' --download_plan_token_duration 900 --download_checkpoint_token_duration 900 --upload_gradient_token_duration 900 --aggregator_pubsub_topic 'aggregator-demo-env-topic'" #kpt
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          capabilities:
            drop:
              - "NET_RAW"
        resources:
          requests:
            cpu: "1500m"
            memory: "8Gi"
            ephemeral-storage: "1Gi"
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - effect: "NoSchedule"
          key: "kubernetes.io/arch"
          operator: "Equal"
          value: "amd64"