# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: Build container images

env:
  CONTAINER_IMAGE_REGISTRY: ghcr.io

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

jobs:
  build-container-images:
    env:
      CONTAINER_IMAGE_ID: "ghcr.io/${{ github.repository }}-${{ matrix.container-images.name }}"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: |
            ${{ env.CONTAINER_IMAGE_ID }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build the ${{ matrix.container-images.name }} container image
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.container-images.context-directory }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Run an instance of the ${{ matrix.container-images.name }} container image
        run: |
          CONTAINER_IMAGE_NAME=${{ fromJSON(steps.docker-build.outputs.metadata)['image.name'] }}
          docker run --rm "${CONTAINER_IMAGE_NAME}"
    strategy:
      matrix:
        container-images:
          - name: devcontainer
            context-directory: .devcontainer
          - name: distributed-fl-simulation-k8s
            context-directory: examples/federated-learning/tff/distributed-fl-simulation-k8s
          - name: image-classification
            context-directory: examples/federated-learning/tff/image-classification
...
