---
name: Release

on:  # yamllint disable-line rule:truthy
  pull_request: null

# Don't grant any access by default
permissions: {}

jobs:
  preview-release-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup authentication token
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" > .github-personal-access-token

      - name: Generate a preview of the release notes
        run: |
          scripts/release-please-dry-run.sh
...
